sudo: required
services:
  - docker
before_install:
  - docker build -t ercee23/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true ercee23/react-test npm run test -- --coverage

after_success:
  - docker build -t ercee23/multi-client ./client
  - docker build -t ercee23/multi-nginx ./nginx
  - docker build -t ercee23/multi-server ./server
  - docker build -t ercee23/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ercee23/multi-client
  - docker push ercee23/multi-nginx
  - docker push ercee23/multi-server
  - docker push ercee23/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-1549263650614
  bucket_path: docker-multi
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY